### ISSUE TITLE
resctrl, frequency 적용 등 미구현파트 구현

### ISSUE THREAD

**Issue by YoonsungNam** [dcslab-snu/bench-launcher#8]
이슈
- resctrl의 시작값을 조정하는 코드가 필요함 (iso-sched의 CAT utility활용)
- 현재 런처 local_config에서 frequency를 입력받지만 입력받은데로 설정값을 수행하지 않음
- static isolation 실험가능한 config.json 생성, 여러 config를 수행할 수 있도록 하는 스크립트의 작성

**Comment by YoonsungNam** [comment]
현재의 ResCtrl의 gen_mask함수에서 생성하는 mask값이 겹치지 않도록 수정해야함

**Comment by isac322** [comment]
@YoonsungNam 지금 master에 `ResCtrl`안에 `gen_mask`함수는 없다고 나오는데 컨트롤러것 말씀하시는거에요?

**Comment by YoonsungNam** [comment]
@isac322 해당 이슈의 변경사항은 issue/8 브랜치에 수정되어 업데이트되고 있음
ResCtrl의 gen_mask에서 cbm_range값을 받도록 되어있으므로, bench_config에 cbm_ranges 필드를 추가함
